# Generated by Django 5.1.6 on 2025-04-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_comment_options_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
