# Generated by Django 5.1.6 on 2025-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_categories_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Дополнительное изображение 1'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Дополнительное изображение 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Основное изображение'),
        ),
    ]
