# Generated by Django 5.1.6 on 2025-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_products_image_2_products_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 3'),
        ),
    ]
